### ISSUE TITLE
Very Fast

### ISSUE THREAD

**Issue by ncinar** [jacksonkr/actionscript#1]
Hi,
I tried another movie clip and successful.
But according to very fast real iPhone
How can I reduce speed

**Comment by jacksonkr** [comment]
I wrote this a long time ago but here's what I think you're looking for. Open [IOSScrollArea](https://github.com/jacksonkr/actionscript/blob/master/com/jacksonkr/ui/IOSScrollArea.as) and look for `MOMENTUM_DEFAULT` and try a number like `1.276`.

**Comment by ncinar** [comment]
Thanks for reply,
I tried and It was exactly as I want
